### ISSUE TITLE
x11-wm/muffin-4.4.3 fails to compile

### ISSUE THREAD

**Issue by oneplusme** [tkemmer/binaryden#1]
I ran into a compile failure in x11-wm/muffin:
cdesktop-enums.h:222: syntax error, unexpected '[' in '        [C_DESKTOP_MEDIA_KEY_MUTE] = "volume-mute",' at '['

which I tracked down to:
 https://github.com/linuxmint/cinnamon-desktop/issues/104

Adding the following diffs (as listed in the issue) into /etc/portage/patches resolved it for me:
https://github.com/linuxmint/muffin/commit/e0471c5dfaa9e1e5d7b6bc66a73184bab212a2c1.patch
https://github.com/linuxmint/muffin/commit/eaacd664855b03517a0406024b18eb9f5a597a9d.patch
https://github.com/linuxmint/muffin/commit/a452ec976f22b1ffba51e934f2d771d0680f6cca.patch

**Comment by tkemmer** [comment]
Thanks, I have added the patches! I had merged muffin before the incompatible gobject-introspection update and didn't notice. ^^

**Comment by oneplusme** [comment]
All working now, thanks. :)
