### ISSUE TITLE
Unable to compile package gnome-extra/cinnamon after update dev-util/meson up to 0.60.2-r1

### ISSUE THREAD

**Issue by Cerberios** [tkemmer/binaryden#10]
Hello there! After update dev-util/meson up to version 0.60.2-r1 I am unable to compile gnome-extra/cinnamon package.
Process falling with error:
....
`Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)

**src/st/meson.build:204:0: ERROR: "install_dir" must be specified when installing a target**

A full log can be found at /tmp/portage/gnome-extra/cinnamon-5.0.7/work/cinnamon-5.0.7-build/meson-logs/meson-log.txt
 * ERROR: gnome-extra/cinnamon-5.0.7::binaryden failed (configure phase):
 *   (no error message)
 * Call stack:
 *     ebuild.sh, line  127:  Called src_configure
 *   environment, line 2963:  Called meson_src_configure
 *   environment, line 2159:  Called die
 * The specific snippet of code:
 *       "${mesonargs[@]}" ) || die
 *
`
I am not sure, will it help, but the same error was occur for package dev-libs/gjs (for now it already fixed)
Please, look over this issue and buzz me if I need provide additional info.
Thanks!

**Comment by tkemmer** [comment]
Thanks for the report! This seems to have been fixed for Cinnamon's master branch already [1]. I will prepare a backport for 5.0.5 in a sec.

[1] https://github.com/linuxmint/cinnamon/commit/8fc2df08b40aa3e1958ed2fde853c50676d8cf48
