### ISSUE TITLE
gnome-extra/cjs-5.2.0 - error - meson.build:541:0: ERROR: "install_dir"

### ISSUE THREAD

**Issue by Cerberios** [tkemmer/binaryden#11]
Hello there!
After update for package gnome-extra/cjs-5.0.1::gentoo --> gnome-extra/**cjs-5.2.0::binaryden*

[ebuild     U  ] gnome-extra/**cjs-5.2.0**::binaryden [**5.0.1::gentoo**] USE="cairo gtk readline sysprof -examples -test" 0 KiB

I got error:
meson.build:541:0: ERROR: "install_dir" must be specified when installing a target (llooks like similar I have reported before)

[cjs-5.2.0-build-Error-meson-log.txt](https://github.com/tkemmer/binaryden/files/7677567/cjs-5.2.0-build-Error-meson-log.txt)

Please, take care!
Thanks!

**Comment by tkemmer** [comment]
Heya, thanks for the report! This absolutely looks like the same error as with Cinnamon and there also exists an official patch for this. I will bump the ebuild in a second!

Seems to be the only other Cinnamon project affected by this, but I will try to recompile everything with the new meson version just to make sure.
