### ISSUE TITLE
x11-libs/xapps-1.8.2 missing dependency on dev-libs/libdbusmenu

### ISSUE THREAD

**Issue by oneplusme** [tkemmer/binaryden#2]
I ran into a build failure in x11-libs/xapps-1.8.2 at configure time, claiming it couldn't find dev-libs/libdbusmenu-gtk

emerging dev-libs/libdbusmenu resolved this.

Suspect there's a missing dependency on dev-libs/libdbusmenu[gtk,introspection] ?

(Apologies for the sudden issue spam.  Just added this overlay due to the cinnamon masking in core.)

**Comment by tkemmer** [comment]
Thanks, I have added the missing dependency (and fixed cairo along the way).
