### ISSUE TITLE
x11-wm/muffin-4.4.3-r1 fails to compile

### ISSUE THREAD

**Issue by nzlosh** [tkemmer/binaryden#3]
muffin fails to compile with the below error.

```configure: error: Package requirements (wayland-server >= 1.1.90) were not met:

No package 'wayland-server' found
```

The system has the wayland use flag globally disabled in make.conf.

**Comment by nzlosh** [comment]
It appears wayland support was removed from the build process in master.  I applied the same modification to local source for muffin and I no longer get the above error.

https://github.com/linuxmint/muffin/commit/f78bf5b309b3d306848f47cc241b31e9399999a7#diff-e05b2f9567e1b07641220a082fddd56bL234

**Comment by nzlosh** [comment]
Looking at the ebuild, it appears there's already a patch to handle disabling wayland and it's being applied:

``` * Applying muffin-4.0-clutter-configure.patch ...                                                                                                                    [ ok ]
 * Applying muffin-4.0-cogl-configure.patch ...                                                                                                                       [ ok ]
````
I suspect the ebuild patches `confiugre.ac` after the autotools have already been run.

By explicitly passing `--enable-wayland-egl-server=no` to the configure script, the build runs successfully.

**Comment by tkemmer** [comment]
Thanks for tracking this down! Muffin should now work again without wayland.
