### ISSUE TITLE
cinnamon-4.4.8-r3 depends on newer dev-python/xapp

### ISSUE THREAD

**Issue by metafarion** [tkemmer/binaryden#5]
I'm not sure of all the details, but it looks like cinnamon-settings might need a newer xapp than is currently stable in portage (1.0.1-r2).  After successfully emerging all the 4.4.x cinnamon packages from binaryden, cinnamon-settings would no longer run
Output:
`Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 27, in <module>
    import SettingsWidgets
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 12, in <module>
    from xapp.SettingsWidgets import SettingsWidget, SettingsLabel
ModuleNotFoundError: No module named 'xapp.SettingsWidgets'`

Upgrading xapp to 1.8.1 fixed this, and downgrading back to 1.0.1-r2 broke it again.  I've confirmed this on two different systems.

**Comment by tkemmer** [comment]
Thanks for pointing this one out! Cinnamon 4.4 requires at least xapps 1.6. The dependency should be fixed now. :)

**Comment by metafarion** [comment]
Hang on though, it wasn't x11-libs/xapps, it was, dev-python/xapp.  My x11-libs/xapps has been 1.4.2 this entire time.  Though I see dev-python/xapp is pulled in by x11-libs/xapps, it doesn't seem to a direct dependency in the ebuild, and x11-libs/xapps-1.6 and newer don't seem to pull in the necessary version of dev-python/xapp on their own.

**Comment by metafarion** [comment]
Hmmm, well perhaps you're right after all.  Though I don't fully understand it, updating x11-libs/xapps to 1.6 ALSO fixed the problem; dev-python/xapp is still 1.0.1.

**Comment by tkemmer** [comment]
This is indeed strange. Glad that it works for you, though! In the ebuild, dev-python/xapp has been a dependency of cinnamon only indirectly via cinnamon-screensaver. I think I should add it explicitly, though, and with a minimum version. I can't find version requirements in the cinnamon repositories, but from my experience, there tend to be intermittent issues with some older versions... Plus, the Linux Mint guys release new xapps and python-xapp versions alongside new Cinnamon releases anyway that I intend to maintain in this overlay, so I will just use those versions as a minimum.
