### ISSUE TITLE
x11-wm/muffin-4.8.0 fails to compile with >=gtk-doc-1.33

### ISSUE THREAD

**Issue by oneplusme** [tkemmer/binaryden#7]
dev-util/gtk-doc-1.33.1 no longer appears to provide the file /usr/share/gtk-doc/data/gtk-doc.make
Without this, x11-wm/muffin-4.8.0 fails when running: automake --add-missing --copy --foreign --force-missing
because doc/reference/clutter/Makefile.am requires gtk-doc.make

Reverting to gtk-doc-1.32-r2 before building works around this.

**Comment by tkemmer** [comment]
Hmm, might this be related to the ebuild/meson configuration you use for gtk-doc? As far as I see it at first glance, the missing gtk-doc.make file should still be installed as part of gtk-doc when the latter was configured with the `autotools_support` option being enabled.

**Comment by oneplusme** [comment]
Hmm.  emerge -pv gtk-doc says:
[ebuild   R    ] dev-util/gtk-doc-1.33.1::gentoo  USE="-doc -emacs -test" PYTHON_SINGLE_TARGET="python3_8 -python3_6 -python3_7 -python3_9" 0 KiB

The (stock) ebuild does contain:

src_configure() {
        local emesonargs=(
                $(meson_use test tests)
                $(meson_use doc yelp_manual)
                -Dautotools_support=false
        )
        meson_src_configure
}

That -D flag is not present in the 1.32 ebuilds (which use a gnome2_src_configure call instead).  If I'm reading that correctly, autotools_support is always disabled now?

I'm not sure I know what I'm talking about enough to raise an upstream (ebuild) bug for this - I assume somebody had a reason to change it, although apparently it's breaking things here.

**Comment by tkemmer** [comment]
Ah, sorry, didn't notice that 1.33.1 has been added to ::gentoo. Yeah, the `-Dautotools_support=false` part seems to be the problem here. Or, more precisely, the files generated with this options are not installed through `dev-util/gtk-doc-am`. I modified the ebuild for 1.33.1 to also install the missing files. Muffin should build now correctly with `dev-util/gtk-doc-1.33.1` and `dev-util/gtk-doc-am-1.33.1-r1`.

**Comment by oneplusme** [comment]
That fixes it for me, thanks. I don't know how we might go about getting that change (or something like it) upstream in -gentoo? I'd guess that missing file might break other things as well.

**Comment by tkemmer** [comment]
Personally, I don't see an apparent reason why gtk-doc and gtk-doc-am should remain split into separate ebuilds. The gtk-doc ebuild could as well just enable/disable autotools support through a USE flag. Let's see what the main tree maintainers will do: https://bugs.gentoo.org/758893

**Comment by tkemmer** [comment]
This issue has been fixed in the main repository. Since the patched gtk-doc-am ebuild from this overlay would cause file collisions with the new gtk-doc-1.33.1-r2::gentoo ebuild, I have removed the former.
