### ISSUE TITLE
gnome-extra/cinnamon-control-center-4.8.0 fails to compile with USE="networkmanager -modemmanager"

### ISSUE THREAD

**Issue by oneplusme** [tkemmer/binaryden#8]
gnome-extra/cinnamon-control-center-4.8.0 with USE="networkmanager -modemmanager" fails to build with the error:
cc-network-panel.c:(.text+0x58e): undefined reference to `net_device_mobile_get_type'

USE="networkmanager modemmanager" or USE="-networkmanager -modemmanager" build correctly.

I guess this is an upstream bug, but it may be worth tying these use flags together?  (I had modemmanager off because I don't need modem support.)

**Comment by tkemmer** [comment]
Okay, so I had a deeper look into the problem and I can confirm that this is an upstream bug. I will open an issue in the upstream bug tracker in a sec, so I guess it will be fixed soon.

For the time being, I will most probably just temporarily require both `networkmanager` and `modemmanager` being enabled/disabled together.

**Comment by oneplusme** [comment]
Thanks!

**Comment by tkemmer** [comment]
Upstream bug: https://github.com/linuxmint/cinnamon-control-center/issues/254
